# Generated by Django 3.2.16 on 2023-01-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mediadrivea_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadrivea',
            name='image',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
