# Generated by Django 3.2.16 on 2023-01-19 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mediadrivea_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadrivea',
            name='image',
            field=models.FileField(max_length=500, upload_to='uploads', validators=[django.core.validators.FileExtensionValidator(['mp4', 'pdf', 'exe', 'jpg', 'png'])]),
        ),
    ]
