# Generated by Django 3.2.16 on 2023-01-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mediadrivea_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediadrivea',
            name='name',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
