# Generated by Django 3.2.16 on 2023-01-19 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mediadrivea_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediadrivea',
            name='video',
            field=models.FileField(max_length=250, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='mediadrivea',
            name='image',
            field=models.FileField(max_length=500, upload_to='uploads', validators=[django.core.validators.FileExtensionValidator(['mp4', 'pdf', 'exe', 'jpg', 'png', 'JPEG', 'SVG', 'mp3'])]),
        ),
    ]
