# Generated by Django 3.2.16 on 2023-01-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230120_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediadrivea',
            name='name',
        ),
    ]
