# Generated by Django 3.2.16 on 2023-01-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_mediadrivea_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadrivea',
            name='video',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='uploads'),
        ),
    ]
