# Generated by Django 3.2.16 on 2023-02-02 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_mediadrivea_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, max_length=250, null=True, upload_to='uploads')),
            ],
        ),
        migrations.AddField(
            model_name='mediadrivea',
            name='created_document_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 14, 26, 2, 888891)),
        ),
        migrations.AlterField(
            model_name='mediadrivea',
            name='image',
            field=models.FileField(max_length=500, upload_to='uploads'),
        ),
    ]
